# Generated by Django 5.1.1 on 2024-11-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_userlogin_remove_customer_email_remove_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
