# Generated by Django 5.1.2 on 2024-11-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_remove_customer_address_remove_customer_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='name',
        ),
    ]
